name: 'shellcheck'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: shellcheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: .
