name: 'shellcheck'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Lint
        uses: pipeline-components/shellcheck@v0.6.0
