name: 'testing'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  basic_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: basic package
        run: sh ./test/basic_test.sh
